# Generated by Django 5.2.6 on 2025-10-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=20, unique=True)),
                ('passport_series', models.CharField(max_length=2)),
                ('passport_number', models.CharField(max_length=7)),
                ('certificate_image', models.ImageField(upload_to='certificates/')),
            ],
        ),
    ]
